name: Test

on:
  push:
    branches: [main]

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Test App
        run: |
          npm ci
          npx jest
